name: Databricks Pull Request
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Databricks CLI
        run: |
          wget -qO- https://packages.databricks.com/databricks-cli/installer.deb.sh | bash
          apt-get install databricks-cli
      - name: Create Databricks workspace
        run: |
          databricks workspace mkdirs /Users/navinkumar.gandhi@agilisium.com/gittodb12
      - name: Download files from GitHub repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: Upload files to Databricks workspace
        run: |
          databricks workspace import_dir ${{ github.workspace }} /Users/navinkumar.gandhi@agilisium.com/gittodb12
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Automated pull request'
          title: 'Update files in Databricks workspace'
          body: 'This pull request updates the files in the Databricks workspace.'
          branch: 'update-databricks-workspace'
          base: 'main'
