name: Import Git repository to Databricks

on:
  push:
    branches: [main]

jobs:
  import-to-databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create pull request in Databricks repository
        uses: databrickslabs/databricks-automation@master
        with:
          token: ${{ secrets.DATABRICKS_TOKEN }}
          command: workspace-import
          source_path: ./data-1
          target_path: /Users/Navinkumar.Gandhi@agilisium.com/new
          overwrite: true
