name: Push data to Databricks

on:
  push:
    branches:
      - main

jobs:
  push-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Databricks CLI
        run: |
          pip install databricks-cli
      - name: Create pull request in Databricks repository
        uses: databrickslabs/databricks-automation@master
        with:
            token: ${{ secrets.DATABRICKS_PAT }}
            command: workspace-import
            source_path: ./data-1
            target_path: /Users/NavinKumar.Gandhi@agilisium.com
            overwrite: true
