name: Create Databricks PR

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Create Databricks PR
        uses: DatabricksInc/github-actions/pull-request@main 
        with:
          token: ${{ secrets.DATABRICKS_TOKEN }}
