name: Pull from GitHub to Databricks

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  push-to-databricks:
    runs-on: ubuntu-latest
    needs: clone
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token

      - name: Clone Databricks repository
        run: |
          databricks workspace export_dir /Repos/Navinkumar.Gandhi@agilisium.com/data-1 /github/workspace/databricks

      - name: Pull changes from GitHub
        run: |
          cd /github/workspace/databricks
          git pull

      - name: Push changes to Databricks
        run: |
          databricks configure --token "$DATABRICKS_TOKEN" --url "$DATABRICKS_HOST"
          databricks workspace import_dir /github/workspace/databricks /Repos/Navinkumar.Gandhi@agilisium.com/data-1 --overwrite
