name: Push to Databricks

on:
  push:
    paths:
      - '**'

env:
  DATABRICKS_HOST: https://agilisium.cloud.databricks.com
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  push_to_databricks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          curl -O https://files.pythonhosted.org/packages/f0/1d/423925d69660118b2c0e8dd1c54cbce2514e7582a6c8b4f7a2f6a64b8cd1/databricks-cli-0.14.3.tar.gz
          tar -xzf databricks-cli-0.14.3.tar.gz
          cd databricks-cli-0.14.3
          python setup.py install

      - name: Push code to Databricks
        run: |
          databricks workspace import_dir . /Users/Navinkumar.Gandhi@agilisium.com --overwrite
